_wandb:
    value:
        cli_version: 0.19.11
        m: []
        mask/class_labels:
            image_with_masks_wandb_delimeter_ground_truth:
                key: image_with_masks_wandb_delimeter_ground_truth
                type: mask/class_labels
                value:
                    "0": background
                    "1": line
            image_with_masks_wandb_delimeter_prediction:
                key: image_with_masks_wandb_delimeter_prediction
                type: mask/class_labels
                value:
                    "0": background
                    "1": line
        python_version: 3.9.22
        t:
            "1":
                - 55
            "2":
                - 55
            "3":
                - 23
                - 55
            "4": 3.9.22
            "5": 0.19.11
            "8":
                - 1
                - 5
            "12": 0.19.11
            "13": linux-x86_64
